platform :ios, '9.0'

target 'Movie' do
  use_frameworks!
  pod 'Alamofire'
  pod 'ObjectMapper'
  pod 'SDWebImage'
  pod 'Reusable'
  pod 'Cosmos'
  pod 'youtube-ios-player-helper'
  pod 'MBProgressHUD'
end
